services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - 'PMA_ARBITRARY=1'
    ports:
      - '8081:80'  
    links:
      - mariadb:mysql
